### ISSUE TITLE
Changes in nested objects not being tracked?

### ISSUE THREAD

**Issue by max-mathieu** [nighca/movue#19]
Hi there, thanks a ton for this integration!

While evaluating Vue with mobx-state-tree, I've been getting issues trying to track changes in nested objects, as if only the things listed in `fromMobx` are defined as reactive.

Then I found [this change](https://github.com/nighca/movue/commit/26fc5b8e7c16aa47b662c85694df2710c9458919) and I am curious about the motivation behind using the shallow option. Was this performance? Other? It looks like vue-rx [does not do that](https://github.com/vuejs/vue-rx/blob/cde4f9d76df8f3e51752595100163d53fc6a82c7/src/mixin.js#L38)

To help, here is my code:
```
  computed: {
    item() {
      return this.project.item
    },
  },
  fromMobx: {
    project() {
      return shop.projects.getFirst()
    },
  },
  methods: {
    updateItem() {
      this.project.setItem(this.newItem)
    }
  }
```
`shop.projects` being a mobx-state-tree store, with a `setItem` function that updates the `project.item`. mobx-state-tree being immutable, `project.item` effectively points to a different observable, but movue does not track the change

Let me know your thoughts

**Comment by max-mathieu** [comment]
Just to add more context: I confirm changing change-detector to set shallow = false makes the above code work

**Comment by nighca** [comment]
Thx for the feedback. We will check that.

**Comment by nighca** [comment]
@max-mathieu Actually it is expected with current realization. MobX and Vue both relies on "define observable property" to make data observable. In your example code, property `project` on `this` is a Vue property, while property `item` on `project` is a MobX property, which means, accessing (calling `getter` of) property `project.item` will not be tracked in Vue's `computed` context.

We can't define a property multi times (only the last definition will work). So if we use `shallow = true` while calling `defineReactive`, it will break MobX's observable mechanism on internal data structure (such as the property `project.item`). That's why we use `shallow = false` instead.

Technically, you should access "MobX property" only in `fromMobx` context. For example:

```js
import { toJS } from 'mobx'

export default {
  fromMobx: {
    project() {
      // toJS converts obervable data to normal Javascript data
      // which will notify movue that the data content got accessed
      return toJS(shop.projects.getFirst())
    },
  }
}
```

But it is not friendly for users to keep that in mind. So we are considering to make some improvement so that your example code will work.

Here are some ideas if you are interested to discuss with us:

1. Use `toJS` by default to convert result of `fromMobx` getters

    This is easy, but may introduce performance issues, as every single change on dep-data will cause result's `toJS` convert and will produce a totally new object (which is not friendly to Vue, either).

2. Create a mirror object on Vue context and use technologies like mobx-state-tree's JSON-Patch to keep it in sync with the result of `fromMobx` getter

What do you think? We really appreciate your feedback.

**Comment by max-mathieu** [comment]
@nighca Sorry to reply only now. We have actually decided to use React instead of Vue for that project, so I got less time to look at movue.
I actually did not have problems with Vue breaking mobx-state-tree, though it has pretty different internals than MobX, so I can't speak for the general case here

**Comment by nighca** [comment]
@max-mathieu Sure, thx.
